"""empty message

Revision ID: 4eaafca38633
Revises: 83229bbf50af
Create Date: 2021-02-13 13:02:55.695647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4eaafca38633'
down_revision = '83229bbf50af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('venue_genres')
    op.drop_table('pastshows')
    op.drop_table('upcomingshows')
    op.drop_table('artist_genres')
    op.drop_table('genres')
    op.add_column('artist', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('artist', 'past_shows_count')
    op.drop_column('artist', 'upcoming_shows_count')
    op.add_column('venue', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('venue', 'past_shows_count')
    op.drop_column('venue', 'upcoming_shows_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('upcoming_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('venue', sa.Column('past_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('venue', 'genres')
    op.add_column('artist', sa.Column('upcoming_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('artist', sa.Column('past_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('artist', 'genres')
    op.create_table('genres',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('genres_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='genres_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('artist_genres',
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genres_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], name='artist_genres_artist_id_fkey'),
    sa.ForeignKeyConstraint(['genres_id'], ['genres.id'], name='artist_genres_genres_id_fkey'),
    sa.PrimaryKeyConstraint('artist_id', 'genres_id', name='artist_genres_pkey')
    )
    op.create_table('upcomingshows',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], name='upcomingshows_artist_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], name='upcomingshows_venue_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='upcomingshows_pkey')
    )
    op.create_table('pastshows',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], name='pastshows_artist_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], name='pastshows_venue_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pastshows_pkey')
    )
    op.create_table('venue_genres',
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genres_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['genres_id'], ['genres.id'], name='venue_genres_genres_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], name='venue_genres_venue_id_fkey'),
    sa.PrimaryKeyConstraint('venue_id', 'genres_id', name='venue_genres_pkey')
    )
    op.drop_table('shows')
    # ### end Alembic commands ###
