"""empty message

Revision ID: 83229bbf50af
Revises: e076c6ba3391
Create Date: 2021-02-11 18:09:15.401426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83229bbf50af'
down_revision = 'e076c6ba3391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('venue', sa.Column('area_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'venue', 'area', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue', type_='foreignkey')
    op.drop_column('venue', 'area_id')
    op.drop_table('area')
    # ### end Alembic commands ###
